### ISSUE TITLE
Special character encoding when writing our XML files

### ISSUE THREAD

**Issue by solomchuk** [ESRIN-RSS/Excel-to-ISO-converter#21]
The script fails to encode some special characters when writing the final XML outputs.

Example string:
"• STRIPMAP HIMAGE (HIM): achieving medium resolution, wide swath imaging, with swath extension **≥**40 km and spatial resolution of 3x3 m2 single look."

The "greater or equal" character causes the following error during script execution:
`UnicodeEncodeError: 'charmap' codec can't encode character '\u2265' in position 6529: character maps to <undefined>`

Solution - explicitly specify UTF-8 as encoding when opening files for writing:
`Line 666: with open(complete_xml_path, 'w', encoding="utf-8") as file:`
...
`Line 670:            with open(complete_json_path, 'w', encoding="utf-8") as file:`

**Comment by vascobnunes** [comment]
@solomchuk i think the solution you suggest will bring problems when we get the 'µ' char. Could you please send me some excel files with and without this char?

**Comment by solomchuk** [comment]
I noticed that with my changes the output XML files have a weird extra character before each 'µ'. However, removing lines 392 and 393 from the existing script while keeping my additions (`with open(complete_xml_path, 'w', encoding="utf-8")`) seems to solve this specific issue:

```
    #elif str(val).find("µ") > 0:
    #    val = val.encode('utf-8').decode('cp1252')
```
[ADAM surface reflectance database v4.0.xlsx](https://github.com/ESRIN-RSS/Excel-to-ISO-converter/files/4261743/ADAM.surface.reflectance.database.v4.0.xlsx)
I used the attached file as input.

**Comment by solomchuk** [comment]
[AATSR Averaged Surface Temperature AST Product-AR.xlsx](https://github.com/ESRIN-RSS/Excel-to-ISO-converter/files/4261755/AATSR.Averaged.Surface.Temperature.AST.Product-AR.xlsx)
This example does not have any 'µ' chars.

**Comment by vascobnunes** [comment]
ok, this seems good. I'm commiting these changes.
