### ISSUE TITLE
Suggestion: add more detailed logging to check_all_green()

### ISSUE THREAD

**Issue by solomchuk** [ESRIN-RSS/Excel-to-ISO-converter#23]
While fixing an issue with some of the input spreadsheets I found it helpful to add a little more details to the logging setup in check_all_green() function. Specifically, whenever a mandatory field with an empty value is found, log the field code/name/value. This will ensure that the person handling the spreadsheet inputs knows what needs fixing specifically.

Code:
```
if fieldcode == mf and fieldvalue is None:
    logger.error("Missing field value: code [{}], name [{}], value [{}]".format(fieldcode, fieldname, fieldvalue))
    count += 1
```
The string formatting syntax above is for Python 3. If compatibility with Python 2 is needed, can use `code [{1}], name [{2}], value [{3}]` instead.

**Comment by vascobnunes** [comment]
Thanks @solomchuk. I added your suggestion. If you have more suggestions like this in the future, you can create Pull Requests if you want.
